### ISSUE TITLE
Errors running builder 'CDT Builder'

### ISSUE THREAD

**Issue by MustajabJafry** [SamsungDForum/NativePlayer#4]
I am currently using 
> Tizen studio 3.2
> pepper SDK version_56 

but when I try to build the project I get following error

`Invoking: NaCl C++ compiler
pnacl-clang++ -I"C:\Users\PC\Downloads\NaCl_SDK_v56\pepper_56/include" -c -g -o "src/player/url_player/url_player_controller.po" "../src/player/url_player/url_player_controller.cc"
../src/player/url_player/url_player_controller.cc:10:10: fatal error: 'player/url_player/url_player_controller.h' file not found
#include "player/url_player/url_player_controller.h"
         ^
1 error generated.
make: *** [src/player/url_player/subdir.mk:17: src/player/url_player/url_player_controller.po] Error 1
`

Does the branch contains libraries for `pepper_56` or do I have to downgrade to `pepper_47`?

**Comment by GrandTeaBrewer** [comment]
Currently master branch contains precompiled libraries for Pepper 47. You have two options, either
- use pepper_47 toolchain, or
- build libraries with pepper_56 and use them instead.

If you choose the latter, all precompiled libraries used in this project are built from [Samsung fork of Webports](https://github.com/SamsungDForum/Webports).

[More context](https://github.com/SamsungDForum/NativePlayer/issues/2#issuecomment-486209638) for this question for others with a similar issue.

**Comment by MustajabJafry** [comment]
Thanks for the reply. I will try this. Can you please tell that whether the native client player supports UDP(multicast) streams or not?

I did some search and found out that samsung tv mostly after `2015` `i.e. J series` have issues with UDP streams.

Unfortunately, most of our playable links are upd based.

**Comment by GrandTeaBrewer** [comment]
Yes, UDP multicast is supported in NaCl as follows:
- since 2017 products (pepper_47 and later) it's supported via PPB_UDPSocket_1_2 interface (see [::JoinGroup()](https://developer.samsung.com/onlinedocs/tv/pepper_47/c/struct_p_p_b___u_d_p_socket__1__2.html#a3012f1d7f38fff9d45925e05850cfdb0), [::LeaveGroup()](https://developer.samsung.com/onlinedocs/tv/pepper_47/c/struct_p_p_b___u_d_p_socket__1__2.html#a5e46591a3a742ee1a9e3de81a76624d3)),
- on products from 2015 and 2016 (pepper_37 and pepper_42) it's supported via PPB_UDPSocketExtension_Samsung_0_1 interface.

You can also use multicast in NaCl app using POSIX sockets (nacl_io library supports this). Regarding interface availability and compatibility, generally nacl_io from toolchains 47+ will determine which of the two interfaces above is available in runtime and will use it. For compatibility reasons PPB_UDPSocketExtension_Samsung_0_1 is also available on 2017+ products, however it's a deprecated API and new apps should be written so that they use PPB_UDPSocket_1_2.

Some links that might be useful:
- [Pepper API reference](https://developer.samsung.com/tv/develop/extension-libraries/nacl/api-references/pepper-api-references),
- [article on using sockets in NaCl](https://developer.samsung.com/tv/develop/extension-libraries/nacl/sample-based-tutorials/sockets-in-cplusplus) (unfortunately only unicast is explained here).

**Comment by MustajabJafry** [comment]
Thank you for the reply.

Actually, I am new to C++ language and we want to use C++ just to embed native player in the app.

I would be much thankful if you can kindly share your email address at this address so I can contact you in person in case help is required

Email is mustajabjafry@gmail.com

**Comment by MustajabJafry** [comment]
Hi @GrandTeaBrewer , I am unable to build the master branch code with pepper_46.

I get following errors:

```
13:29:30 **** Build of configuration Debug for project NativePlayer ****
make all 
Building file: ../src/player/url_player/url_player_controller.cc
Invoking: NaCl C++ compiler
pnacl-clang++ -I"/include" -I"E:\NativePlayer\src" -I"E:\NativePlayer\third_party\include" -I"E:\NativePlayer\inc" -c -c -std=gnu++0x -g -o "src/player/url_player/url_player_controller.po" "../src/player/url_player/url_player_controller.cc"
/bin/sh: pnacl-clang++: command not found
make: *** [src/player/url_player/subdir.mk:17: src/player/url_player/url_player_controller.po] Error 127

13:29:30 Build Finished (took 273ms)
```

Please help.
